### PR TITLE
Activate rss feed

### LINKED ISSUE #262: RSS feed
**Is this a BUG REPORT or FEATURE REQUEST?**:
feature

**What happened**:
No global nor per section feed is available.

**What you expected to happen**:
Per section and one global feed available via RSS.

### PR DESCRIPTION
**Pull request by mpourismaiel**
**What this PR does / why we need it**:
Activate rss files

**Which issue this PR fixes**:
fixes #262 

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by stp-ip** [comment]
Taking a look at the actual index: https://deploy-preview-403--syna-demo.netlify.com/index.xml
I think a global index doesn't really make sense. Should updates to the page really be within the rss feed?
Maybe we need config to only have section based feeds?
Or do you think global is a good default and then we can add configuration to make the feed less spammy?

**Comment by stp-ip** [comment]
Ahh ok. Mhh so hugo does have the global rss and the per section rss...
https://deploy-preview-403--syna-demo.netlify.com/dev/blog/index.xml
That one actually looks good.

**Comment by mpourismaiel** [comment]
I'm not really familiar with how a feed should look like. This is done by Hugo's default RSS template.

**Comment by stp-ip** [comment]
Let's say usually articles are included in the feed, but static pages and their updates would most likely not.
Let me think about this for a bit.

**Comment by stp-ip** [comment]
Idea:
* add `rss = true` on the section level
* use rss template to link to the page of the content not to a single content fragment
* use rss template to show the description of the page or the first content fragment
* global rss index as a combination of the various section rss pages
* per section rss index

**Pull request closed without merging**
