### PR TITLE
Move markdown content from <p> to <div>

### LINKED ISSUE #31: Move from `<p>` to `<div>` for anything that could contain markdown content
**Is this a BUG REPORT or FEATURE REQUEST?**:
feature

**What happened**:
Currently `<p>` is being used in some places, which might lead to issues.

**What you expected to happen**:
Use `<div>` instead of `<p>`.

### PR DESCRIPTION
**Pull request by lauragift21**
**What this PR does / why we need it**:
Check for all possible occurrences of paragraph tag using markdown content and change to div tag.

**Which issue this PR fixes** *(optional - uncomment and add issue)*:
fixes #31 

**Special notes for your reviewer**:
 Already fixed in #25 but this is an overall check.

### CODE REVIEW

**Comment by stp-ip** [comment]
So that's the only one left? Let me double check and then we can merge and close another issue \o/

**Comment by stp-ip** [comment]
There is one more instances as far as I can see, but doesn't seem it should be a problem, but wanted to get your opinion on it: https://github.com/okkur/syna/blob/5afa06e98e85b7343e0452fcaebf1b94bfc1f34b/layouts/partials/fragments/hero.html#L54

**Comment by lauragift21** [comment]
Yeah, we should totally change this one too. I did an overall check with the input for <p> so I missed this one.

**Pull request merged**
