### PR TITLE
Add tiled layout to list fragment

### LINKED ISSUE #282: Add tiling mode to list fragment
**Is this a BUG REPORT or FEATURE REQUEST?**:
feature

**What happened**:
List fragment displays pages only in a list layout.

**What you expected to happen**:
Ability to render pages in tiling mode as well as list mode.

**How to reproduce it (as minimally and precisely as possible)**:
Use list layout to see pages in a section.

**Environment**:
- Syna Theme version: v0.12

### PR DESCRIPTION
**Pull request by mpourismaiel**
**What this PR does / why we need it**:
List fragment now supports rendering in tiled mode. Hell of a messy code though.

image

image

**Which issue this PR fixes**:
fixes #282 

**Special notes for your reviewer**:

**Release note**:
```release-note
- list: Now supports tiled mode
```

### CODE REVIEW

**Comment by stp-ip** [comment]
I feel they should be the same height similar to how we do it for portfolio items. Feels weird them having different heights. Will look at the code in a bit.

**Comment by stp-ip** [comment]
Code looks not perfect, but reasonable. Let's merge #269 first and then make it work with the changes introduced. You are adding a few changes again that were already in 269 it seems.

**Comment by mpourismaiel** [comment]
I fixed the conflicts, fixed the heights so cards in the same row have the same height and added a new `read_more @default false` variable to show the read more link.

**Comment by stp-ip** [comment]
How does the read_more usage look like?

**Comment by stp-ip** [comment]
From a design it looks good. Still need to look at the read_more design.
From a code perspective. I'll let that sit for a bit and do another review.

**Comment by stp-ip** [comment]
So for the read_more config:
`read_more = true` -> show "Read more..." if truncated
`read_more = false` -> never show "Read more..."

**Comment by stp-ip** [comment]
Also the design of "Read more..." is great. Just missed it in the screenshot.

**Comment by mpourismaiel** [comment]
Fixed `read_more` and refactored a part of the code regarding where the content is (if it's inside the index file or another resource around the index file).

**Comment by mpourismaiel** [comment]
@stp-ip The conflicts have been fixed.

**Pull request merged**
