### PR TITLE
Add dev examples for images not loading and unconfiged ones

### PR DESCRIPTION
**Pull request by stp-ip**
**What this PR does / why we need it**:

**Special notes for your reviewer**:

**Release note**:

```release-note

```

### CODE REVIEW

**Comment by stp-ip** [comment]
The case for not loading images aka bad connection: https://5b703784c96592748e389ebe--syna-demo.netlify.com/dev/missing-images/

The case for unconfigured images: https://5b703784c96592748e389ebe--syna-demo.netlify.com/dev/unconfigured-images/

With this demo we can create a few issues and fix both cases to make them look good.

**Comment by mpourismaiel** [comment]
Fantastic. For missing images, should we display an error message or render it as is?

**Comment by stp-ip** [comment]
I would say for non configured images, render as is. There might be a specific reason for that and as long as it doesn't break the layout, that should be ok.

**Comment by mpourismaiel** [comment]
@stp-ip What about missing images? For non configured we mostly don't render the `img` tag altogether (logos and portfolio fragment require images so doesn't make sense to remove them, just make them better looking).

**Comment by stp-ip** [comment]
Missing images I think it maybe should fallback to sort of a blank placeholder aka keep the layout as if an image would be present. Such as an empty circle for member etc.

**Pull request merged**
