### PR TITLE
Make ToC fragment work standalone outside slots

### LINKED ISSUE #420: [toc] Fragment doesn't work outside of slots
**Is this a BUG REPORT or FEATURE REQUEST?**:
bug

**What happened**:
ToC fragment only works in slots. The content variable inside it doesn't work.

**What you expected to happen**:
For ToC fragment to work everywhere.

**How to reproduce it (as minimally and precisely as possible)**:
Try to use ToC fragment without slots.

**Anything else we need to know?**:
The variable in the fragment only contains an string. It should contain the Page type instead of String type.

**Environment**:
- Syna Theme version:  
- Hugo version:  
- Others:

### PR DESCRIPTION
**Pull request by mpourismaiel**
**What this PR does / why we need it**:
Makes ToC fragment standalone and adds `/dev/toc` page to test the cases that ToC fragment supports.

**Which issue this PR fixes**:
fixes #420

### CODE REVIEW

**Comment by stp-ip** [comment]
Still reviewing, but this breaks: https://deploy-preview-422--syna-demo.netlify.com/dev/empty-subitems/
Also the warning within the helper is tailored towards members only instead of more broadly phrased.

**Comment by stp-ip** [comment]
Will take another fresh look at the code change tomorrow.

**Comment by mpourismaiel** [comment]
That would be great. Also added the margin to the warning helper.

**Comment by stp-ip** [comment]
Still breaks: https://deploy-preview-422--syna-demo.netlify.com/dev/empty-subitems/

**Comment by stp-ip** [comment]
This breaks the collapsible functionality.

**Comment by mpourismaiel** [comment]
Will switch to this after v0.14 fixes.
I check collapse in FAQ and navbar. Where does it break?
Will fix the warnings in empty subitems.

**Comment by stp-ip** [comment]
The toc items seem not to support collapsible with the recent code changes in this PR. I might be wrong so. Will take another testing and review run at it tonight.

**Comment by mpourismaiel** [comment]
Oh it's because of the conflict not being fixed. On it.

**Comment by stp-ip** [comment]
Will do another test run tomorrow. Hopefully I can do some merges also. :)

**Pull request merged**
