### PR TITLE
Fix linking in docs

### PR DESCRIPTION
**Pull request by stp-ip**
**What this PR does / why we need it**:
Migrate linking to use Hugo style references.

**Which issue this PR fixes** *(optional - uncomment and add issue)*:
fixes okkur/website#7

**Special notes for your reviewer**:

**Release note**:

```release-note

```

### CODE REVIEW

**Comment by stp-ip** [comment]
This currently breaks with our `/dev` content. We probably need to prefix all content in their with `dev-` or similar.

Happy for other solutions. On that note. Do have have the generation script checked into code? @mpourismaiel

**Comment by mpourismaiel** [comment]
This looks great. Thanks a lot.

**Comment by mpourismaiel** [comment]
There seems to be a problem with the build though.

**Comment by stp-ip** [comment]
Yes see comment above. This is due to our /dev/ sub dir.

**Comment by stp-ip** [comment]
This needs a solution as manually fixing this feels problematic and it keeps the live site unsynced from the Syna code.

**Comment by stp-ip** [comment]
Any ideas? Happy to take another look at an idea next week.

**Comment by mpourismaiel** [comment]
I don't really have an idea. I'm migrating to v0.60 so we might be able to fix it in there if there's a hidden solution somewhere.

**Comment by stp-ip** [comment]
Prefixing the dev pages with "dev-" would probably help make them not matched and therefore work around the duplicate warning.
What do you think?

**Comment by stp-ip** [comment]
Merging this now. Voice your concern now or hold it for ever.

**Comment by mpourismaiel** [comment]
I thought I commented on this one. There's no problem with adding a prefix for specificity's sake. lgtm.

**Pull request merged**
