### PR TITLE
Add support for pagination

### LINKED ISSUE #322: [list] List fragment doesn't support pagination in list pages
**Is this a BUG REPORT or FEATURE REQUEST?**:
feature

**What happened**:
It's not possible to navigate in archives if the total pages are more than the amount rendered in the page.

**What you expected to happen**:
To have the ability to paginate archives and navigate between them.

**How to reproduce it (as minimally and precisely as possible)**:
Checkout a list page containing list fragment with it's `count` set to a number less than pages in the section.

### PR DESCRIPTION
**Pull request by mpourismaiel**
**What this PR does / why we need it**:
Add support for pagination in list fragment

List fragment would show pagination if the page is using list layout and doesn't have a count variable set up.

**Which issue this PR fixes**:
fixes #322 

**Special notes for your reviewer**:

**Release note**:
```release-note
- list: Pagination is now supported
```

### CODE REVIEW

**Comment by mpourismaiel** [comment]
This is WIP. Section leaves are not paginated.

**Comment by mpourismaiel** [comment]
`is_list` is needed since in normal pages pagination doesn't work.

**Comment by stp-ip** [comment]
Will think about another way to check for list without actually needing to provide the `is_list`

**Comment by stp-ip** [comment]
Happy to merge after v0.13.0 is tagged.

**Pull request merged**
