### PR TITLE
Add shortcodes

### LINKED ISSUE #95: Simplify code and helper snippets via shortcodes
**Is this a BUG REPORT or FEATURE REQUEST?**:
feature

**What happened**:
Currently we have quite a bit of duplication in the various fragments.

**What you expected to happen**:
Reduce duplication and move helper snippets into shortcodes.

**Anything else we need to know?**:
https://gohugo.io/templates/shortcode-templates/

### PR DESCRIPTION
**Pull request by mpourismaiel**
**What this PR does / why we need it**:
Adds semi-shortcode partials that would allow for DRY code and some functions

**Which issue this PR fixes**:
fixes #95 

**Special notes for your reviewer**:
This only implements partials for logo and img (with fallthrough support).

### CODE REVIEW

**Comment by mpourismaiel** [comment]
@stp-ip Should I add fall through for item and member fragments as well? Or a new partial for loading images.

Also loading partials has one issue. Using `dict` for arguments makes it so that list of variables would make the line maybe reach 200 characters in length. Even using variables to store larger calculations doesn't make it much smaller. Maybe this isn't that good of an idea (using partials) and we should use it just for situations like resource fallthough.

**Comment by mpourismaiel** [comment]
Also the `partial/shortcodes/img.html` would handle resource fallthrough for images and I guess for now there is no other resource that we may want to fallthrough. So maybe with this, #124 would be resolved as well.

**Comment by stp-ip** [comment]
Great for fighting with shortcodes and the partial workaround. The syntax of the "function" call is long and hard to understand. Question is, if that is better then code duplication.

`{{ partial "shortcodes/img.html" image }}` would feel easier, while complicating the preparation code of $image.
$image itself would have the following data embed:
* .image <-- filename to look for
* .text <-- alt name
* .link <-- optional linking
* .class <-- maybe optional class data

Not sure about class itself, but condensing that would be great.

Might have been a bad idea on my part to try deduplicating the fallback code. Would love to hear other thoughts as well. @lauragift21

**Comment by mpourismaiel** [comment]
How should I make a structured data containing those variables? 

Does hugo have any such thing planned? Something like custom functions or shortcodes or even better variable declarations?

**Comment by stp-ip** [comment]
Nothing that comes to mind. Will look through the possibilities tomorrow.

**Comment by mpourismaiel** [comment]
@stp-ip I'm still lost on this. I guess it would be better to push this issue a bit so Hugo may come up with a better solution. Using this style is really horrible.

**Comment by stp-ip** [comment]
Yeah I think duplicating the code is the better choice for now. Ok let's close this one here and go with implementing fallthrough for all images via code duplication instead.

**Comment by mpourismaiel** [comment]
So we're going to push this to 0.12?
-- 
Regards,
Mahdi Pouresmaiel

**Comment by stp-ip** [comment]
Push the refactoring to post v0.11. Probably depends on a good Hugo way to do that. So no set milestone for now.

**Pull request closed without merging**
