### PR TITLE
Add category support for content-single and content-split fragments

### PR DESCRIPTION
**Pull request by mpourismaiel**
**What this PR does / why we need it**:
Add category support for content-single and content-split fragments

**Release note**:
```release-note
Add category support to content (single and split) fragments
```

### CODE REVIEW

**Comment by stp-ip** [comment]
Clarification:
about-split is adjusted to the background color it seems, but about isn't.

**Comment by mpourismaiel** [comment]
That's because someone didn't save the file after they changed the color switch. Also the color switch is based on whether the background color is dark or not. Should I do something else?

Will add a page and push in a moment.

**Comment by stp-ip** [comment]
Nope dark or not should be enough for now. Similar to how we do it with the other switches.

**Comment by stp-ip** [comment]
LGTM

**Pull request merged**
