### PR TITLE
Add stripe with events

### LINKED ISSUE #9: Create payment fragment (stripe)
**Is this a BUG REPORT or FEATURE REQUEST?**:
feature

**What happened**:
No payment fragment.

**What you expected to happen**:
Payment fragment based on stripe.

**How to reproduce it (as minimally and precisely as possible)**:
Look for a payment fragment.

**Anything else we need to know?**:
Also needs backend component hosted.

**Environment**:
- Syna Theme version:  v0.7.0
- Hugo version:  v0.30.2

### LINKED ISSUE #218: Add event fragment
**Is this a BUG REPORT or FEATURE REQUEST?**:
feature

**What happened**:
Currently showcasing events is hard.

**What you expected to happen**:
Make showcasing events easier.

**Anything else we need to know?**:
* full event calendar also outputting JSON and webcal (specific page to make custom outputs easier?)
* fragment to showcase x next events being populated by JS from JSON

So we have the fragment with simple html + JS to populate from full JSON and we have the full event html, which uses JS to populate it from full JSON. Both link to a webcal link.

### PR DESCRIPTION
**Pull request by mpourismaiel**
**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional - uncomment and add issue)*:
fixes #9 
fixes #218 

**Special notes for your reviewer**:
I closed the payment PR since this is based on that. Keeping the note on the previous one here:

To not forget the meta data would be helpful:
* [ ]  page it was triggered from aka "about.example.com/donation/"
* [ ] product name

**Release note**:
```release-note
- stripe: Added new stripe fragment
- events: Added pubsub to the theme. Fragments can now seamlessly communicate with each other
```

### CODE REVIEW

**Comment by mpourismaiel** [comment]
Fixed the validation issues. Had to update the dependency.

Regarding the url, we can receive that from the request headers, can't we? I'll add the value to the request body as well.

Regarding the product however, I'm not really sure where to add it. Do you have any ideas?

**Comment by stp-ip** [comment]
For the product I would use meta-data. Might not be supported within our function, haven't checked. If it isn't we can open an issue and look into it in another PR.

**Comment by mpourismaiel** [comment]
I send the title of the pricing plan if a plan is selected. The product is set to empty by default in the stripe fragment. We don't make use of it in the function, only log it so when we publish the function it's shown in there.

**Comment by stp-ip** [comment]
Before merge let's cleanup the conflicts first ;)

**Comment by mpourismaiel** [comment]
Resolved conflicts and added small documentation.

**Pull request merged**
