### PR TITLE
Make list fragment collapsible by a variable

### LINKED ISSUE #416: [list, toc] Nested content should be collapsible
**Is this a BUG REPORT or FEATURE REQUEST?**:
feature

**What happened**:
ToC and List fragment can have nested content which would add much more data than what's actually needed for the user to see.

**What you expected to happen**:
The nested content should be collapsible through a variable in the fragment's frontmatter.

**How to reproduce it (as minimally and precisely as possible)**:
Checkout `/docs` page of the demo (after #414 is merged).

### PR DESCRIPTION
**Pull request by mpourismaiel**
**What this PR does / why we need it**:
Adds new collapsible variable to list fragment (makes the content of article collapsible)
Makes ToC not render anything if it doesn't have any content

**Which issue this PR fixes**:
fixes #416 

**Release note**:
```release-note
- list: List fragment can now be collapsible
```

### CODE REVIEW

**Comment by stp-ip** [comment]
Not expanding, when title is overflowing into next line.

**Comment by stp-ip** [comment]
Should the icon change depending on the state aka between collapsed and non collapsed?

**Comment by mpourismaiel** [comment]
@stp-ip Mostly we don't have animations in the page. I think the only animation that we have outside of bootstrap is for modal and portfolio's hover. Should I add it here?

**Comment by stp-ip** [comment]
Mhh let's keep it for now. Still leaves the bug, when a title overflows.

**Comment by mpourismaiel** [comment]
Do you mean the "Fragment implementation" article? I think the content in it has only one header and the code for ToC only render the ToC if it has more than one header. Will check why it renders the chevron.

**Comment by mpourismaiel** [comment]
Fixed the issue. The problem was with the ToC fragment rendering without content.

**Pull request merged**
