### PR TITLE
Add support for netlify custom recaptcha

### LINKED ISSUE #247: [contact] make custom recaptcha work with netlify
**Is this a BUG REPORT or FEATURE REQUEST?**:
feature

**What happened**:
Currently having a custom recaptcha doesn't work with netlify.

**What you expected to happen**:
Custom recaptcha with netlify.

### PR DESCRIPTION
**Pull request by lauragift21**
**What this PR does / why we need it**:
It adds support for netlify custom recaptcha

**Special notes for your reviewer**:

**Release note**:

```release-note
Add support for netlify custom recaptcha
```

### CODE REVIEW

**Comment by lauragift21** [comment]
Yeah this one is valid.

**Comment by lauragift21** [comment]
Alright, I'll add that.

**Comment by stp-ip** [comment]
Looks good . One thing is the formatting, which might not be done yet.

**Comment by lauragift21** [comment]
Oh okay. I didn't have an idea of the general rule for removing whitespace thought it was just to remove from both sides.

**Comment by stp-ip** [comment]
Yeah we have to find a better long term solution for whitespace. Unfortunately html isn't something we can use the new pipelines for.

LGTM

**Pull request merged**
