### PR TITLE
Fix image size in items fragments' columns

### LINKED ISSUE #717: Fragment "items": title  doesn't render correct with text + asset
bug

Consider this snippet:
```
+++


title = "Agile"

weight = 10

[asset]
image = "scrum.svg" 

+++

<p>One step at a time will guide us to the moon. Adjusting direction in regular intervals is key to effectively navigate. Having happy customers is the ultimate goal. Check out the <a href="https://agilemanifesto.org/">Agile Manifesto</a>.</p>
```
This renders like this:

image

Doesn't look that nice. I helped myself with this workaround:
```

+++


title = ""

weight = 10

[asset]
image = "scrum.svg" 

+++

<br><br><br><br>
<h4>Agile</h4>
<br>

<p>One step at a time will guide us to the moon. Adjusting direction in regular intervals is key to effectively navigate. Having happy customers is the ultimate goal. Check out the <a href="https://agilemanifesto.org/">Agile Manifesto</a>.</p>
```

which renders much better (Will add screenshot later).

### PR DESCRIPTION
**Pull request by mpourismaiel**
**What this PR does / why we need it**:
This is the best fix I could come up with. I really can't understand why flexbox behaved the way it did. With `display: grid` it was easier to fix the issue and as far as I can see the results are the same as they were when using `display: flex`.

**Which issue this PR fixes**:
fixes #717 

**Special notes for your reviewer**:

**Release note**:
```release-note
- items: Fix overflowing image issue
```

### CODE REVIEW

**Comment by stp-ip** [comment]
This is probably harder to test as this is mainly visual. Any ideas? Manual test page or just leave it without a test?
Besides the test. lgtm

**Comment by mpourismaiel** [comment]
I'm not really sure how to test it. I can't think of a way to create an automated test for it. A dev page might be a good idea but since writing tests for helpers I'm thinking of automating testing for other dev pages and don't like the idea of going through dev pages every now and then to make sure stuff works. We can create a dev page for now, it's better than nothing. If you don't have any suggestions we can create them and go ahead with merging the PR with dev page in it.

**Comment by stp-ip** [comment]
Ok let's go with the dev page only and see, if we can later automate visual and function testing on those "manual" pages. in the future. Thanks for working through ideas on tests.

**Comment by mpourismaiel** [comment]
@stp-ip Alright I created the dev page as well. Will think on how to automate the verification process.

**Pull request merged**
