### PR TITLE
Recaptcha fixes

### LINKED ISSUE #3: Rework captcha support
**Is this a BUG REPORT or FEATURE REQUEST?**:
bug

**What happened**:
Even with the captcha enabled, spam requests still come in.

**What you expected to happen**:
All spam form submissions shouldn't be possible.

**How to reproduce it (as minimally and precisely as possible)**:
Enable the captcha and wait for spam.

**Environment**:
- Syna Theme version:  v0.7.0
- Hugo version:  0.30.2

### PR DESCRIPTION
**Pull request by stp-ip**
**What this PR does / why we need it**:
Recaptcha needs a bit if rework to function correctly.

**Which issue this PR fixes** *(optional - uncomment and add issue)*:
fixes #3

**Special notes**:
Still needs styling and conflict resolution. The errors not showing is already open as issue.

### CODE REVIEW

**Comment by stp-ip** [comment]
Let's do the error messages in a separate PR.

**Comment by stp-ip** [comment]
The styling on the recaptcha. Probably just make it responsive on mobile and fit a bit better into the overall fragment. Right now it sits awkwardly on the left side without fitting into any specific area.

**Comment by mpourismaiel** [comment]
I tried aligning it with the button. It might be a bit better. Check them out.

screenshot-2018-03-15_08-01-43

screenshot-2018-03-15_08-06-27

**Comment by stp-ip** [comment]
Styling looks good. Great work.
Conflicts still need resolving.

**Comment by stp-ip** [comment]
You opened another PR. Ok let's close it here than.

**Pull request closed without merging**
