### PR TITLE
Add support for icon in portfolio fragment

### LINKED ISSUE #649: [portfolio] Icon asset is not supported
**Is this a BUG REPORT or FEATURE REQUEST?**:
bug

**What happened**:
The portfolio fragment does support the asset declaration, but not the icon from that.

**What you expected to happen**:
Icon support for portfolio.

**How to reproduce it (as minimally and precisely as possible)**:
Set an icon instead of an image to asset.

**Anything else we need to know?**:
Any other fragments that support asset, but not the full spec including icon?

### PR DESCRIPTION
**Pull request by mpourismaiel**
**What this PR does / why we need it**:
Add support for icons in portfolio fragment

**Which issue this PR fixes**:
fixes #649 

**Release note**:
```release-note
- portfolio: added support for icons
```

### CODE REVIEW

**Comment by stp-ip** [comment]
On the modal we also need the icon support or at least remove the image code or it will load a broken image.

Besides that it looks good.

**Comment by mpourismaiel** [comment]
It should be fixed. It's not really a good approach for the displaying of the icon in the modal but I can't think of anything else at the moment.

**Comment by stp-ip** [comment]
`` Still shows up and breaks ;)

But the icon in the modal is already good. Happy with that solution, even if it's not perfect.

**Comment by mpourismaiel** [comment]
My bad. Pushed a fix for that.

**Pull request merged**
