### PR TITLE
WIP: Create events fragment and stream

### LINKED ISSUE #218: Add event fragment
**Is this a BUG REPORT or FEATURE REQUEST?**:
feature

**What happened**:
Currently showcasing events is hard.

**What you expected to happen**:
Make showcasing events easier.

**Anything else we need to know?**:
* full event calendar also outputting JSON and webcal (specific page to make custom outputs easier?)
* fragment to showcase x next events being populated by JS from JSON

So we have the fragment with simple html + JS to populate from full JSON and we have the full event html, which uses JS to populate it from full JSON. Both link to a webcal link.

### PR DESCRIPTION
**Pull request by mpourismaiel**
**What this PR does / why we need it**:

**Which issue this PR fixes**:
fixes #218

**Special notes for your reviewer**:
**DO NOT MERGE.** Under heavy construction.

@stp-ip Please review and let me know what you think. We can take several approaches. This one seems the best to me. We have to register events where they ought to happen, as showcased in the pricing fragment. The events fragment registers the js script which would register all event emitters and publish their event to any listener out there.

**Release note**:

```release-note

```

### CODE REVIEW

**Comment by mpourismaiel** [comment]
In this iteration the main stuff are `events.js`, `events.html` and `pricing.html`.

**Comment by stp-ip** [comment]
Looks good so far. Took a bit longer due to the JS. Will take another step at the JS as I want to be sure, I get the details.

Also to test this and in general event actions. I think a /dev/ specific fragment, that just prints the event data would be helpful. What do you think?

**Comment by mpourismaiel** [comment]
So you agree adding event listeners with `[data-event]`?

**Comment by stp-ip** [comment]
That seemed like a good choice. Mapping the action to the actiol HTML event attributes.

**Comment by stp-ip** [comment]
Superseded by #444

**Pull request closed without merging**
